# tup1 = (1,2,3,4,5,1,2,1,2,1)
# print(type(tup1))
# #print (tup1[1:3])
# print(tup1.index(5))
# print(tup1.count(2))
t = ("c","d","a","a","b","b","a")
print(t.count("d"))
l = list(t)
l.sort()
print(l)